### ISSUE TITLE
For lines xPadding should be dynamic based on maxY

### ISSUE THREAD

**Issue by flatiron32** [yaronn/blessed-contrib#19]
If I have Y values greater than 4 chars wide, I have to manually override the padding to get the values to appear correctly. I should be able to set the y values and let blessed-contrib do the work for me.

**Comment by flatiron32** [comment]
I have tried my hand at implementing something, but am struggling with two things:
1. The intended meaning of xPadding, yPadding, xLabelPadding, and yLabelPadding.
2. How wide is a printed character.

**Comment by yaronn** [comment]
I agree this would be nice to calculate it automatically. One issue is that if you sometimes have 4 digit values and sometimes don't the chart might move all the time. One way is to have it stick with the largest padding it ever used.

xPadding is the X offset from the external widget box where the graph will start (y is similar). e.g. x offset of 5 means the whole chart (including labels) will start 5 'pixels' from the left.

xLabelPadding means how far from the axis the label will start to write itself. this value will be substracted from the intended label start. So the actual x start of each y axis label is xPadding - xLabelPadding. y is similar.

Each character is in width of 2 pixels and height of 4.

**Comment by flatiron32** [comment]
The xLabelPadding I think is most confusing because it controls where the y
labeled will be drawn.

**Comment by flatiron32** [comment]
I understand your concern about the moving axis. However, my company is a huge user (and originator) of Graphite. We look at these graphs continuously and I have never noticed this issue. I think it is quite rare.

**Comment by yaronn** [comment]
Thanks for all the PRs! I will merge in the next few days when I have free
time.

Just wanted to let you know one of the design considerations, and please
tell me if you think your code may affect it (did not look yet). Every
character contains 8 braile dots (2 width X 4 height). All of them must be
in the same color according ANSI rules. This means that when the data line
is very low (close to zero) it may find itself in the same 'character' (8
pixels) as the X axis baseline, which would mean that one line color would
override the other in that section. AFAIR I solved it by always adding a
dummy 1-2 pixels between the axis line and the data line. Anyway just
thought to mention since you are doing this (very needed) work in the line
chart internals. Thanks again!

On Thu, Feb 5, 2015 at 6:02 PM, Jacob Tomaw <notifications@github.com>
wrote:

> I understand your concern about the moving axis. However, my company is a
> huge user (and originator) of Graphite. We look at these graphs
> continuously and I have never noticed this issue. I think it is quite rare.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/blessed-contrib/issues/19#issuecomment-73071426>
> .
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by yaronn** [comment]
Thanks @flatiron32, great work! I have pushed a new version with your improvements.
