### ISSUE TITLE
Lines with callbacks

### ISSUE THREAD

**Issue by flatiron32** [yaronn/blessed-contrib#23]
What do you think about modifying the syntax of a line to take an optional callback and interval values?The callback would be function() --> [labels_arr, values_arr]. This would be wrapped in a function to call it and use the return value to call setData. This wrapper would be setImmediate and setInterval.

**Comment by yaronn** [comment]
Hi @flatiron32 

Can you show me a usage example of this API? For example how would this look in the new API:

    var line = contrib.line(
             { style: 
               { line: "yellow"
               , text: "green"
               , baseline: "black"}
             , xLabelPadding: 3
             , xPadding: 5
             , label: 'Title'})
       var data = {
             x: ['t1', 't2', 't3', 't4'],
             y: [5, 1, 7, 5]
          }
       screen.append(line) //must append before setting data
       line.setData(data.x, data.y)

**Comment by flatiron32** [comment]
That exposes an issue where the line must be appended to the screen before adding the data. Let's assume this is guarded against in setData by not attempting to draw is there is not a context, instead of throwing an error as today. But the line might need to know about the screen anyway to get this to work.
That would look like
```javascript
var line = contrib.line(
  { style: 
    { line: "yellow"
      , text: "green"
      , baseline: "black"}
    , xLabelPadding: 3
    , xPadding: 5
    , label: 'Title'}, function {
  return {
    x: ['t1', 't2', 't3', 't4'],
    y: [5, 1, 7, 5]
  }});
screen.append(line) //must append before setting data
```
That is not terrebly interesting because the data is static. What I have though is this today.
```javascript
var metric = 'PROD-WM.streambase.gash.all.jiniIn.count';

var line = contrib.line({
  label: metric,
});

screen.append(line);

function getData() {
  http.get('http://graphite.prod.o.com/render/?from=-1d&format=json&target=' + metric, function(res) {
    var data = "";
    res.on('data', function(d) {
      data += d;
    });
    res.on('end', function() {
      try {
        var datapoints = JSON.parse(data)[0].datapoints;
        var times = [];
        var values = [];
        for (var i = 0; i < datapoints.length; i++) {
          var datapoint = datapoints[i];
          times.push(new Date(datapoint[1] * 1000).toLocaleTimeString());
          values.push(datapoint[0]);
        }
        line.setData(times, values);
        screen.render();
      } catch (e) {
        // console.log("Got error: " + e.message);
      }
    });
  }).on('error', function(e) {
    // console.log("Got error: " + e.message);
  });
}
setImmediate(getData);
setInterval(getData, 60000);
```

This could be transformed into
```javascript
var metric = 'PROD-WM.streambase.gash.all.jiniIn.count';

function getData() {
  http.get('http://graphite.prod.o.com/render/?from=-1d&format=json&target=' + metric, function(res) {
    var data = "";
    res.on('data', function(d) {
      data += d;
    });
    res.on('end', function() {
      try {
        var datapoints = JSON.parse(data)[0].datapoints;
        var times = [];
        var values = [];
        for (var i = 0; i < datapoints.length; i++) {
          var datapoint = datapoints[i];
          times.push(new Date(datapoint[1] * 1000).toLocaleTimeString());
          values.push(datapoint[0]);
        }
        return [times, values];
      } catch (e) {
        return e;
      }
    });
  }).on('error', function(e) {
    return e;
  });
}
var line = contrib.line({
  label: metric,
}, getData);
```

Ultimately I want this because I want to extend blessed-contrib/line to a class that is specific for Graphite data where the only thing in the constructor is the name of the metric.

**Comment by yaronn** [comment]
Hi @flatiron32 

The new API is great for dynamic dashboards. I see a few issues, let me know what you think:

1. Since the callback function is async it cannot use "return", it must get a callback parameter and call it
2. The concept of interval does not fit static dashboards
3. In dynamic dashboards it may not be desired to start drawing data immediately but only after some initialization. Premature calling of the callback may lead to undesired results.

One option is to support both APIs. So callback/interval could be in the options:

    var line = contrib.line({
      label: metric,
      callback: getData,
      interval: 1000
    });

now if a callback and interval are specified they will be used. we should not call getData before the chart has been added to the screen (there is an event for this or we can check context). getData should provide a callback parameter. What do you think?

**Comment by flatiron32** [comment]
I like these ideas. I will code this up to further the conversation.

**Comment by flatiron32** [comment]
Have a look at this branch. https://github.com/flatiron32/blessed-contrib/tree/callbackLines

**Comment by yaronn** [comment]
Hi, can you show me a sample usage code of the new properties?

**Comment by flatiron32** [comment]
```
var blessed = require('blessed');
var contrib = require('blessed-contrib');
var http = require('http');
var screen = blessed.screen();

var metric = 'PROD-WM.streambase.gash.all.jiniIn.count';

function getData(line) {
  http.get('http://graphite.prod.o.com/render/?from=-1d&format=json&target=' + metric, function(res) {
    var data = "";
    res.on('data', function(d) {
      data += d;
    });
    res.on('end', function() {
      try {
        var datapoints = JSON.parse(data)[0].datapoints;
        var times = [];
        var values = [];
        for (var i = 0; i < datapoints.length; i++) {
          var datapoint = datapoints[i];
          times.push(new Date(datapoint[1] * 1000).toLocaleTimeString());
          values.push(datapoint[0]);
        }
        line.setData(times, values);
        screen.render();
      } catch (e) {
      }
    });
  }).on('error', function(e) {
  });
}

screen.append(new contrib.line({
  label: metric,
  callback: getData,
  interval: 600,
}));

screen.key([ 'escape', 'q', 'C-c' ], function(ch, key) {
  return process.exit(0);
});

screen.render();
```

**Comment by yaronn** [comment]
Thanks @flatiron32 . Since the getData method needs to call line.setData anyway, I am not sure any more how much the new API saves the end user. It seems it only saves the call to the setInterval, but instead the user needs to add some parameters. What is the motivation in having everything in the ctor? It is not how other widgets work (though they can be changed if required) and it also gives user less flexibility/control over when and how things really happen.

In addition, I think this:

    setImmediate(options.callback(self));

should be:

    setImmediate(function() {option.callbak(self)})

and also the setInterval. Otherwise it will only call the method once.

also calling immeddiate / interval should only be done once the 'attached' event has been called, see this example: 

https://github.com/yaronn/blessed-contrib/blob/master/widget/map.js

I think the latter also means that immediate should always be true and should not be a parameter - since user cannot control when exactly it will start anyway.

As I mentioned above, please let me know if the current API can answer your needs as is.

**Comment by flatiron32** [comment]
"What is the motivation in having everything in the ctor?" (Or a callback at all really.)

I am not sure now. My OOD instinct tells me that a line should know how to update itself. However like you said, the callback currently has to know how to update the line, which is not better. It only exchanges a direct call to setInterval for an option.

**Comment by yaronn** [comment]
No problem. I'll leave this defect open for now and we can decide at a later stage if this is a necessary change.
