### ISSUE TITLE
About encoding problems

### ISSUE THREAD

**Issue by hustcer** [yaronn/blessed-contrib#50]
Hi,

Thanks for the great work, but it seems to have some encoding problems, when I set the table label to:
```javascript
table = contrib.table({
        label : '你好',
    })
```
It just didn't display as it should be, any ideas? Thanks.

**Comment by yaronn** [comment]
Can you send a screenshot? If the characters are not displayed,  does it
also happens with blessed.box?

**Comment by hustcer** [comment]
Here is a snapshot for the unicode characters problem:
![blessed](https://cloud.githubusercontent.com/assets/1161607/8073250/26155b1e-0f55-11e5-9712-bc8f41a4497a.png)
Thanks!

**Comment by yaronn** [comment]
Thanks Justin

I won't have access to check this in the next 2 weeks.

Please try to add a blessed box element with the same content (try the
blessed hello world). Possibly there is a blessed setting for this.

**Comment by xcezzz** [comment]
@hustcer 
Take a look at the `fullUnicode` option on the blessed.screen instantiation.

fullUnicode - allow for rendering of East Asian double-width characters, utf-16 surrogate pairs, and unicode combining characters. this allows you to display text above the basic multilingual plane. this is behind an option because it may affect performance slightly negatively. without this option enabled, all double-width, surrogate pair, and combining characters will be replaced by '??', '?', '' respectively. (NOTE: iTerm2 cannot display combining characters properly. blessed simply removes them from an element's content if iTerm2 is detected).

**Comment by hustcer** [comment]
@xcezzz Thanks very much, It works, and it seems that iTerm2 can display well too.

**Comment by xcezzz** [comment]
Cool glad it works!
