### ISSUE TITLE
Version 2.1.5 hasn't been published?

### ISSUE THREAD

**Issue by hustcer** [yaronn/blessed-contrib#51]
Hi,

After running `npm info blessed-contrib`, the latest version I got is 2.0.5, and the master branch version is 2.1.5, seemed has't been published. There is a bug in 2.0.5 and has been fixed in 2.1.5: in version 2.0.5 the first row in table won't not be displayed until you press `page down` key, but 2.1.5 is Okay. When will you release the newest version? Thanks

**Comment by xcezzz** [comment]
You can specify the github repo to npm install instead of just
'blessed-contrib'.... or in package.json as the version# and then run npm
install. you can see how I used it in my ceph dashboard since I have a few
new features in my blessed-contrib fork that it uses that he hasn't merged
to main branch

Look at package.json
https://github.com/xcezzz/blessed-ceph-dash

**Comment by hustcer** [comment]
I got it, Thanks very much. And it's not quite convenient.

**Comment by yaronn** [comment]
Hi @hustcer, you can now use version 2.2.0 with all the latest goodies by @xcezzz

**Comment by hustcer** [comment]
Great! Thanks
